### ISSUE TITLE
Email from new window not sent when observe.before or observe.after for send_message is defined

### ISSUE THREAD

**Issue by JerryBels** [KartikTalwar/gmail.js#238]
Hey guys, hey @KartikTalwar friend :)

So, continuing to work on my Chrome extension, I felt upon that issue. When you use a compose window in a new window (either by clicking on a mail adress sent to you in a previous mail, or by ctrl+clic on "New Message") and then try to send the mail, a very strange behavior shows up...

IF and only IF you have defined something like 

    gmail.observe.before('send_message', function(url, body, data, xhr) {
        // Even if you don't add anything here the bug still occurs !
    });

Same goes with `after`. Then, when you click on "send" button, the "sending..." label shows up and never disappears, and after something like 10 seconds an arror appears in the console : 

`MT_VIEW_DATA not set`

I absolutely don't get what that means, if anyone can help me that would be great. As usual, when I will figure it out, I will send a pull request with the correction.

Thanks,
JB

**Comment by KartikTalwar** [comment]
hey @JerryBels I'm pretty occupied until next Monday but if I get time between then I can take a look at it, otherwise will be looking into this next week

**Comment by JerryBels** [comment]
No rush buddy, don't worry, take your time :)

**Comment by nwaarbroek** [comment]
We have the same issue. We try to observe multiple events but when sending an email from a new window it results in not responding interface or even worse. Gmail gives a message: "Ooops... the system encountered a problem. (#009) - Retrying in ... Look like this issue is a bit bigger then just the observer 'send_message'.

**Comment by JerryBels** [comment]
@aesedepece I don't know if it's the same bug, but it's possible :)

@KartikTalwar hello my friend, did you have time to look into it ? I tried but drown fast enough ^^

**Comment by shaharpan** [comment]
To solve this I have implemented this(It will stop from crashing but not solve the issue): 
if (window.opener && window.opener !== window) {
  //fix for when in popup
} else {
//add scripts or whatever you are doing
}

**Comment by JerryBels** [comment]
So the issue is not solved yet. @KartikTalwar anything new from your side ?

**Comment by aakankshabhujbal** [comment]
@nwaarbroek I am facing same issue. Did you find any solution to this?

**Comment by nwaarbroek** [comment]
We stripped down gmail.js to the basic needs we had. We could not point out
an exact location in the source where this issue occure so we decided to
strip down gmail.js and only keep the functionality we needed. We had a
working solution, but in the end we decided it's not stable enough to go in
production.

Met vriendelijke groet / with kind regards,

*Niek Waarbroek*
+31 6 16 790 968

**Comment by aakankshabhujbal** [comment]
Hi. I removed `gmail.observe.before('send_message',` form my code. But still I am getting same issue. Email sending still hangs. What is cause of this? @KartikTalwar Did you looked into this issue?

**Comment by JerryBels** [comment]
@aakankshabhujbal I would say it's probably the case, yes. I guess the observers are broken on any popup window. It looks like @KartikTalwar don't have time for us these days, which is understandable - everyone has a real life to look after, right ? :) I'm sure he will eventually solve this when he has the time for it.

**Comment by aakankshabhujbal** [comment]
@JerryBels I was debugging it from 2 days, just came to know that if I remove `observe.on("open_email"` from my code, email sent successfully. I think we need to dig into observers more. Are you still working on this issue?

**Comment by JerryBels** [comment]
@aakankshabhujbal I will but only in 2 or 3 weeks. I hope the Grand Master of that repos will show up and solve it before though ^^

**Comment by garris** [comment]
This is probably fixed by #284

**Comment by JerryBels** [comment]
Fixed indeed, was waiting for tonight to be able to test :) Thanks @garris , you're a champion !

**Comment by garris** [comment]
Great to hear!  Cheers.
